#!/bin/bash
# Simple Test Guide - Step by Step Instructions

clear
echo "═══════════════════════════════════════════════════════════════════════"
echo "  DISTRIBUTED COMPUTING SYSTEM - MANUAL TEST GUIDE"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "You need to open 5 SEPARATE TERMINAL WINDOWS and run these commands:"
echo ""
echo "───────────────────────────────────────────────────────────────────────"
echo "TERMINAL 1: Worker Node 1"
echo "───────────────────────────────────────────────────────────────────────"
echo "cd /home/aromal/Desktop/MAIN_PROJECT_FINAL"
echo "python3 simulated_node.py --name Worker1 --offset 0"
echo ""
echo "───────────────────────────────────────────────────────────────────────"
echo "TERMINAL 2: Worker Node 2"
echo "───────────────────────────────────────────────────────────────────────"
echo "cd /home/aromal/Desktop/MAIN_PROJECT_FINAL"
echo "python3 simulated_node.py --name Worker2 --offset 1 --simulate-load"
echo ""
echo "───────────────────────────────────────────────────────────────────────"
echo "TERMINAL 3: Worker Node 3"
echo "───────────────────────────────────────────────────────────────────────"
echo "cd /home/aromal/Desktop/MAIN_PROJECT_FINAL"
echo "python3 simulated_node.py --name Worker3 --offset 2"
echo ""
echo "───────────────────────────────────────────────────────────────────────"
echo "TERMINAL 4: Discovery Service (Module 1)"
echo "───────────────────────────────────────────────────────────────────────"
echo "cd /home/aromal/Desktop/MAIN_PROJECT_FINAL/module1_discovery"
echo "python3 main.py"
echo ""
echo "───────────────────────────────────────────────────────────────────────"
echo "TERMINAL 5: Distribution Service (Module 2)"
echo "───────────────────────────────────────────────────────────────────────"
echo "cd /home/aromal/Desktop/MAIN_PROJECT_FINAL/module2_distribution"
echo "python3 main.py --mode interactive"
echo ""
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "ONCE ALL TERMINALS ARE RUNNING, in Terminal 5 type:"
echo ""
echo "  >> create 10 3      ← Create 10 tasks with priority 3"
echo "  >> distribute       ← Distribute tasks to nodes"
echo "  >> status           ← Show system status"
echo "  >> nodes            ← Show node performance details"
echo "  >> quit             ← Exit"
echo ""
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "Press any key to continue..."
read -n 1 -s
echo ""
